#pragma once
#include "EspFileSystem.h"
#include "Global.h"
#include "Utils/Pretty.h"
#include "Utils/WiFiUtils.h"
#include "AsyncWebServer.h"
#include "StandWebServer.h"
#include "classes/sendJson.h"
#include "classes/NotAsync.h"
